export const BANNER_SHOW_REQUEST = "BANNER_SHOW_REQUEST"
export const BANNER_SHOW_SUCCESS = "BANNER_SHOW_SUCCESS"
export const BANNER_SHOW_FAIL = "BANNER_SHOW_FAIL"


export const BANNER_EDIT_REQUEST = "BANNER_EDIT_REQUEST"
export const BANNER_EDIT_SUCCESS = "BANNER_EDIT_SUCCESS"
export const BANNER_EDIT_FAIL = "BANNER_EDIT_FAIL"



export const BANNER_UPDATE_REQUEST = "BANNER_UPDATE_REQUEST"
export const BANNER_UPDATE_SUCCESS = "BANNER_UPDATE_SUCCESS"
export const BANNER_UPDATE_FAIL = "BANNER_UPDATE_FAIL"
export const BANNER_UPDATE_RESET = "BANNER_UPDATE_RESET"

export const BANNER_DETELE_REQUEST = "BANNER_DETELE_REQUEST"
export const BANNER_DETELE_SUCCESS = "BANNER_DETELE_SUCCESS"
export const BANNER_DETELE_FAIL = "BANNER_DETELE_FAIL"

export const BANNER_CREATE_REQUEST = "BANNER_CREATE_REQUEST"
export const BANNER_CREATE_SUCCESS = "BANNER_CREATE_SUCCESS"
export const BANNER_CREATE_FAIL = "BANNER_CREATE_FAIL"
export const BANNER_CREATE_RESET = "BANNER_CREATE_RESET"