export const NEWS_SHOW_REQUEST = "NEWS_SHOW_REQUEST"
export const NEWS_SHOW_SUCCESS = "NEWS_SHOW_SUCCESS"
export const NEWS_SHOW_FAIL = "NEWS_SHOW_FAIL"


export const NEWS_DETAILS_REQUEST = "NEWS_DETAILS_REQUEST"
export const NEWS_DETAILS_SUCCESS = "NEWS_DETAILS_SUCCESS"
export const NEWS_DETAILS_FAIL = "NEWS_DETAILS_FAIL"


export const NEWS_UPDATE_REQUEST = "NEWS_UPDATE_REQUEST"
export const NEWS_UPDATE_SUCCESS = "NEWS_UPDATE_SUCCESS"
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL"
export const NEWS_UPDATE_RESET = "NEWS_UPDATE_RESET"

export const NEWS_DETELE_REQUEST = "NEWS_DETELE_REQUEST"
export const NEWS_DETELE_SUCCESS = "NEWS_DETELE_SUCCESS"
export const NEWS_DETELE_FAIL = "NEWS_DETELE_FAIL"

export const NEWS_CREATE_REQUEST = "NEWS_CREATE_REQUEST"
export const NEWS_CREATE_SUCCESS = "NEWS_CREATE_SUCCESS"
export const NEWS_CREATE_FAIL = "NEWS_CREATE_FAIL"
export const NEWS_CREATE_RESET = "NEWS_CREATE_RESET"