export const NEWS_SHOW_REQUEST = "NEWS_SHOW_REQUEST"
export const NEWS_SHOW_SUCCESS = "NEWS_SHOW_SUCCESS"
export const NEWS_SHOW_FAIL = "NEWS_SHOW_FAIL"


export const NEWS_DETAILS_REQUEST = "NEWS_DETAILS_REQUEST"
export const NEWS_DETAILS_SUCCESS = "NEWS_DETAILS_SUCCESS"
export const NEWS_DETAILS_FAIL = "NEWS_DETAILS_FAIL"